Event.create(name: "1. First Engagement at Chambersburg Pike", description: "Around 7:30 a.m., the first shots of the battle ring out just Northwest of Gettysburg at intersection of Knoxlyn Rd and US Rt. 30 Chambersburg. Union General John Buford's cavalry men engage lead elements of Confederate General Henry Heth's division. As Buford is pushed back, Union Major General John Reyonds arrives with two brigades of the Union First Corps in an effort to slow Heth's advancing army. As fighting intensifies, Reynolds, who at the time was the highest ranking Union general on the battlefield, is killed by a bullet through the base of his skull. Following the death of Reynolds, Major General Abner Doubleday assumes command as the fighting lasts until noon. 
After this pause, Heth's division reengaged Union forces around 2:30 p.m. after adding the brigades of Pettigrew and Colonel John Brockenbrough. Evenutally these combined forces prove to be too much for the First Corp, and they are driven back from the woods into the streets of Gettysburg.", date: "July 1st, 1863", union_leader: "Brig. General John C. Robinson.", confederate_leader: "General Robert E. Rodes", union_army: 550, confederate_army: 800, url: "https://padresteve.files.wordpress.com/2014/05/z_maritato_ironbrigadeforward1.jpg?w=584")
Event.create(name: "2. Oak Hill and Attacks North of Town", description: "As fighting took place on the west side of town, Confederate General Robert E. Rodes arrived at Oak Hill in the North and proceeded to engage Union forces under the command of Brig. Gen. John C. Robinson. Though Rodes has a larger army by the numbers, his attacks were poorly coordinated, allowing Union troops to repulse Confederate advances and for Major General Oliver O. Howard to arrive with his 11th Corp in support. 
Confederate General Jubal A. Early would eventually arrive in support of the rebels on the Northeast side of town, applying pressure on the Union's far right flank. Despite these attacks, early on the Union lines generally hold under extremely heavy pressure. As the day drags on, however, Rodes and Early's combined attacks eventually become too much for Union forces, and the right flank folds under this pressure.
", date: "July 1st, 1863", union_leader: "Pickel Martin", confederate_leader: "JEB Stuart", union_army: 1000, confederate_army: 720, url: "https://www.irishcentral.com/uploads/article/126970/MI_Irish_Brigade_gettysburg.jpg?t=1562142525")
Event.create(name: "3. Union Retreat to Cemetary Hill", description: "Around mid-to-late afternoon, the Union forces find themselves fighting a losing battle on both their right and left flanks. Originally forming a semi-circle that stretched from the Northeast side of town to the West, the arrival of General Lee and increase in Confederate troops was enough to rally both General Rodes and General Heth into another major engagement. Heavy fighting in Herbst's Woods and Seminary Ridge put overwhelming pressure on Union forces, despite the fact that many veteran regiments were attempting to hold their positions. By 4:30 p.m., it became clear to Union General Doubleday that their position was untenable and that casualties were increasing at an alarming rate. Doubleday orders a withdrawal towards the East to an area known as Cemetery Hill, a local burial ground. Some Union soliders escape via an unfinished railroad bed while others, far less fortunate, find themselves trapped in the streets of Gettysburg has they attempted to escape through the town. At Cemetery Hill, Major General Oliver Otis Howard leaves a brigade and an array of cannons. As evening draws near, Confederate forces continue to probe the Union's new position, but hold off attacking.", union_leader: "Joshua Lawrence Chamberlain", confederate_leader: "Some Dude", union_army: 550, confederate_army: 800, url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Culps_Hill_July_3_Edwin_Forbes.jpg/1200px-Culps_Hill_July_3_Edwin_Forbes.jpg")
Event.create(name: "4. Battle of Devils Den", description: "This is a test to see if the 4th data can be fetched. No need to worry.", date: "July 2nd, 1863", union_leader: "Joshua Lawrence Chamberlain", confederate_leader: "Some Dude", union_army: 550, confederate_army: 800)
Event.create(name: "5. Little Round Top", description: "This is a test to see if the 5th data can be fetched. No need to worry.", date: "July 2nd, 1863", union_leader: "Joshua Lawrence Chamberlain", confederate_leader: "Some Dude", union_army: 550, confederate_army: 800, url: "https://cdn.shopify.com/s/files/1/0442/4785/products/Hero_of_Little_Round_Top_grande.jpg?v=1449256134")
Event.create(name: "6. Western Calvary Engagement", description: "This is a test to see if the 6th data can be fetched. No need to worry.", date: "July 2nd, 1863", union_leader: "Joshua Lawrence Chamberlain", confederate_leader: "Some Dude", union_army: 550, confederate_army: 800)
Event.create(name: "7. Picketts Charge", description: "This is a test to see if the 7th data can be fetched. No need to worry.", date: "July 3rd, 1863", union_leader: "Joshua Lawrence Chamberlain", confederate_leader: "Some Dude", union_army: 550, confederate_army: 800)
Event.create(name: "8. Retreat to Virginia", description: "This is a test to see if the 8th data can be fetched. No need to worry.", date: "July 3rd, 1863", union_leader: "Joshua Lawrence Chamberlain", confederate_leader: "Some Dude", union_army: 550, confederate_army: 800)
Event.create(name: "9. Gettysburg Address", description: "This is a test to see if the 9th data can be fetched. No need to worry.", date: "July 3rd, 1863", union_leader: "Joshua Lawrence Chamberlain", confederate_leader: "Some Dude", union_army: 550, confederate_army: 800)

Scenario.create(description: "Imagine you are Confederate Calvary General JEB Stuart, known as General Lee's eyes and ears for scouting out Union positions. Lee has ordered that you ", option_one: "Run down the hill as fast as you can!", option_two: "Stay back and hope Meade sends reinforcements", answer_one: "You successfully route the enemy and have them in retreat!", answer_two: "Reinforcements did not arrive in time. You have been outflanked!", event_id: 1)
Scenario.create(description: "1. Testing Scenario Data", option_one: "Run down the hill as fast as you can!", option_two: "Stay back and hope Meade sends reinforcements", answer_one: "You successfully route the enemy and have them in retreat!", answer_two: "Reinforcements did not arrive in time. You have been outflanked!", event_id: 2)
Scenario.create(description: "1. Testing Scenario Data", option_one: "Run down the hill as fast as you can!", option_two: "Stay back and hope Meade sends reinforcements", answer_one: "You successfully route the enemy and have them in retreat!", answer_two: "Reinforcements did not arrive in time. You have been outflanked!", event_id: 3)
Scenario.create(description: "1. Testing Scenario Data", option_one: "Run down the hill as fast as you can!", option_two: "Stay back and hope Meade sends reinforcements", answer_one: "You successfully route the enemy and have them in retreat!", answer_two: "Reinforcements did not arrive in time. You have been outflanked!", event_id: 4)
Scenario.create(description: "1. Testing Scenario Data", option_one: "Run down the hill as fast as you can!", option_two: "Stay back and hope Meade sends reinforcements", answer_one: "You successfully route the enemy and have them in retreat!", answer_two: "Reinforcements did not arrive in time. You have been outflanked!", event_id: 5)
Scenario.create(description: "1. Testing Scenario Data", option_one: "Run down the hill as fast as you can!", option_two: "Stay back and hope Meade sends reinforcements", answer_one: "You successfully route the enemy and have them in retreat!", answer_two: "Reinforcements did not arrive in time. You have been outflanked!", event_id: 6)
Scenario.create(description: "1. Testing Scenario Data", option_one: "Run down the hill as fast as you can!", option_two: "Stay back and hope Meade sends reinforcements", answer_one: "You successfully route the enemy and have them in retreat!", answer_two: "Reinforcements did not arrive in time. You have been outflanked!", event_id: 7)
Scenario.create(description: "1. Testing Scenario Data", option_one: "Run down the hill as fast as you can!", option_two: "Stay back and hope Meade sends reinforcements", answer_one: "You successfully route the enemy and have them in retreat!", answer_two: "Reinforcements did not arrive in time. You have been outflanked!", event_id: 8)
Scenario.create(description: "1. Testing Scenario Data", option_one: "Run down the hill as fast as you can!", option_two: "Stay back and hope Meade sends reinforcements", answer_one: "You successfully route the enemy and have them in retreat!", answer_two: "Reinforcements did not arrive in time. You have been outflanked!", event_id: 9)

Comment.create(title: "CaptainJilliams", content: "TESTING A COMMENT BRO", user_id: 1, event_id: 1)
Reply.create(title: "CaptainJilliams", content: "Just over here testing a reply mate.", comment_name: "CaptainJilliams", user_id: 1, event_id: 1, comment_id: 1)